INSERT INTO generos (nome) VALUES ('ficção histórica');
INSERT INTO generos (nome) VALUES ('novela');
INSERT INTO generos (nome) VALUES ('fantasia');
INSERT INTO generos (nome) VALUES ('mistério');
INSERT INTO generos (nome) VALUES ('saga da família');
INSERT INTO generos (nome) VALUES ('fantasia, ficção infantil');
INSERT INTO generos (nome) VALUES ('aventura');
INSERT INTO generos (nome) VALUES ('detetive');
INSERT INTO generos (nome) VALUES ('thriller misterioso');
INSERT INTO generos (nome) VALUES ('amadurecimento');
INSERT INTO generos (nome) VALUES ('romance');
INSERT INTO generos (nome) VALUES ('autoajuda');
INSERT INTO generos (nome) VALUES ('realismo mágico');
INSERT INTO generos (nome) VALUES ('romance');
INSERT INTO generos (nome) VALUES ('ficção infantil');
INSERT INTO generos (nome) VALUES ('manual');
INSERT INTO generos (nome) VALUES ('romance infantil');
INSERT INTO generos (nome) VALUES ('literatura infantil');
INSERT INTO generos (nome) VALUES ('novel histórico, mystery');
INSERT INTO generos (nome) VALUES ('guerra, suspense');
INSERT INTO generos (nome) VALUES ('sexologia');
INSERT INTO generos (nome) VALUES ('literatura infantil');
INSERT INTO generos (nome) VALUES ('novella, auto-ajuda');
INSERT INTO generos (nome) VALUES ('literatura infantil, livro de figuras');
INSERT INTO generos (nome) VALUES ('ensaio/literatura');
INSERT INTO generos (nome) VALUES ('romance gótico do sul e educacional');
INSERT INTO generos (nome) VALUES ('horror gótico, saga da família');
INSERT INTO generos (nome) VALUES ('ciência popular, antropologia, astrofísica, cosmologia, filosofia, história');
INSERT INTO generos (nome) VALUES ('romance filosófico, jovem adulto');
INSERT INTO generos (nome) VALUES ('thriller de mistério');
INSERT INTO generos (nome) VALUES ('romance realista socialista');
INSERT INTO generos (nome) VALUES ('romance histórico');
INSERT INTO generos (nome) VALUES ('não ficção histórica, autobiografia, memórias, bildungsroman / withing of age, literatura judaica');
INSERT INTO generos (nome) VALUES ('saga da família romântica');
INSERT INTO generos (nome) VALUES ('literatura cristã');
INSERT INTO generos (nome) VALUES ('romance educacional, ficção histórica');
INSERT INTO generos (nome) VALUES ('romance, tragédia');
INSERT INTO generos (nome) VALUES ('novel gótico');
INSERT INTO generos (nome) VALUES ('distópico, ficção política, ficção científica social');
INSERT INTO generos (nome) VALUES ('ficção');
INSERT INTO generos (nome) VALUES ('ficção adulta jovem');
INSERT INTO generos (nome) VALUES ('romance histórico para jovens adultos');
INSERT INTO generos (nome) VALUES ('autoajuda, motivacional, fábula comercial, psicologia, liderança, parábola');
INSERT INTO generos (nome) VALUES ('ciência popular');
INSERT INTO generos (nome) VALUES ('romance biográfico');
INSERT INTO generos (nome) VALUES ('novo espiritual da nova era');
INSERT INTO generos (nome) VALUES ('romance romântico para jovens adultos');
INSERT INTO generos (nome) VALUES ('filme de ação');
INSERT INTO generos (nome) VALUES ('romance criminal');
INSERT INTO generos (nome) VALUES ('romance romance');
INSERT INTO generos (nome) VALUES ('romance adulto jovem, aventura, distópico, ficção científica');
INSERT INTO generos (nome) VALUES ('romance adulto jovem, aventura, guerra, ficção científica, thriller de ação');
INSERT INTO generos (nome) VALUES ('romance japonês');
INSERT INTO generos (nome) VALUES ('romance de ficção científica');
INSERT INTO generos (nome) VALUES ('autobiografia');
INSERT INTO generos (nome) VALUES ('romance de thriller criminal');
INSERT INTO generos (nome) VALUES ('romance de guerra');
INSERT INTO generos (nome) VALUES ('desconhecido');
INSERT INTO generos (nome) VALUES ('novella alegórica satírica, sátira política, ficção distópica, romana à clave');
INSERT INTO generos (nome) VALUES ('novel semi-autobiográfico');
INSERT INTO generos (nome) VALUES ('memórias');
INSERT INTO generos (nome) VALUES ('literatura infantil, livro de figuras, ficção');
INSERT INTO generos (nome) VALUES ('romance feminista');
INSERT INTO generos (nome) VALUES ('guia de gravidez');
INSERT INTO generos (nome) VALUES ('novelas picaresque, armas de educação, sátira, robinsonada');
INSERT INTO generos (nome) VALUES ('romance para jovens adultos');
INSERT INTO generos (nome) VALUES ('romance de regência clássica, romance');
INSERT INTO generos (nome) VALUES ('literatura de viagem');
INSERT INTO generos (nome) VALUES ('romance de comédia escura satírica inacabada');
INSERT INTO generos (nome) VALUES ('livro de figuras infantis');
INSERT INTO generos (nome) VALUES ('novel romântico');
INSERT INTO generos (nome) VALUES ('romance de fantasia infantil');
INSERT INTO generos (nome) VALUES ('ciências sociais, antropologia, psicologia');
INSERT INTO generos (nome) VALUES ('mistério de assassinato de maior idade');
INSERT INTO generos (nome) VALUES ('novel autobiográfico');
INSERT INTO generos (nome) VALUES ('ficção adulta jovem');
INSERT INTO generos (nome) VALUES ('ficção histórica, romance de guerra');
INSERT INTO generos (nome) VALUES ('erótica');
INSERT INTO generos (nome) VALUES ('ficção científica');
INSERT INTO generos (nome) VALUES ('ficção distópica');
INSERT INTO generos (nome) VALUES ('horror');
