INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('A Tale of Two Cities', 'English', 1859, 200.00, 1, 1);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Little Prince (Le Petit Prince)', 'French', 1943, 200.00, 2, 2);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Harry Potter and the Philosopher''s Stone', 'English', 1997, 120.00, 3, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('And Then There Were None', 'English', 1939, 100.00, 4, 4);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Dream of the Red Chamber (紅樓夢)', 'Chinese', 1791, 100.00, 5, 5);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Hobbit', 'English', 1937, 100.00, 6, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Lion, the Witch and the Wardrobe', 'English', 1950, 85.00, 7, 6);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('She: A History of Adventure', 'English', 1887, 83.00, 8, 7);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Vardi Wala Gunda (वर्दी वाला गुंडा)', 'Hindi', 1992, 80.00, 9, 8);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Da Vinci Code', 'English', 2003, 80.00, 10, 9);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Harry Potter and the Chamber of Secrets', 'English', 1998, 77.00, 3, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Harry Potter and the Prisoner of Azkaban', 'English', 1999, 65.00, 3, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Harry Potter and the Goblet of Fire', 'English', 2000, 65.00, 3, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Harry Potter and the Order of the Phoenix', 'English', 2003, 65.00, 3, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Harry Potter and the Half-Blood Prince', 'English', 2005, 65.00, 3, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Harry Potter and the Deathly Hallows', 'English', 2007, 65.00, 3, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Alchemist (O Alquimista)', 'Portuguese', 1988, 65.00, 11, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Catcher in the Rye', 'English', 1951, 65.00, 12, 10);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Bridges of Madison County', 'English', 1992, 60.00, 13, 11);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Ben-Hur: A Tale of the Christ', 'English', 1880, 50.00, 14, 1);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('You Can Heal Your Life', 'English', 1984, 50.00, 15, 12);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('One Hundred Years of Solitude (Cien años de soledad)', 'Spanish', 1967, 50.00, 16, 13);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Lolita', 'English', 1955, 50.00, 17, 14);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Heidi', 'German', 1880, 50.00, 18, 15);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Common Sense Book of Baby and Child Care', 'English', 1946, 50.00, 19, 16);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Anne of Green Gables', 'English', 1908, 50.00, 20, 17);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Black Beauty', 'English', 1877, 50.00, 21, 18);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Name of the Rose (Il Nome della Rosa)', 'Italian', 1980, 50.00, 22, 19);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Eagle Has Landed', 'English', 1975, 50.00, 23, 20);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Watership Down', 'English', 1972, 50.00, 24, 3);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Hite Report', 'English', 1976, 50.00, 25, 21);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Charlotte''s Web', 'English', 1952, 50.00, 26, 15);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Ginger Man', 'English', 1955, 50.00, 27, 14);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Tale of Peter Rabbit', 'English', 1902, 45.00, 28, 22);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Jonathan Livingston Seagull', 'English', 1970, 44.00, 29, 23);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Very Hungry Caterpillar', 'English', 1969, 43.00, 30, 24);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('A Message to Garcia', 'English', 1899, 40.00, 31, 25);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('To Kill a Mockingbird', 'English', 1960, 40.00, 32, 26);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Flowers in the Attic', 'English', 1979, 40.00, 33, 27);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Cosmos', 'English', 1980, 40.00, 34, 28);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Sophie''s World (Sofies verden)', 'Norwegian', 1991, 40.00, 35, 29);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Angels & Demons', 'English', 2000, 39.00, 10, 30);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Kane and Abel', 'English', 1979, 37.00, 36, 14);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('How the Steel Was Tempered (Как закалялась сталь)', 'Russian', 1932, 36.40, 37, 31);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('War and Peace (Война и мир)', 'Russian', 1869, 36.00, 38, 32);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Adventures of Pinocchio (Le avventure di Pinocchio)', 'Italian', 1881, 35.00, 39, 6);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Diary of Anne Frank (Het Achterhuis)', 'Dutch', 1947, 35.00, 40, 33);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Your Erroneous Zones', 'English', 1976, 35.00, 41, 12);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Thorn Birds', 'English', 1977, 33.00, 42, 34);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Purpose Driven Life', 'English', 2002, 33.00, 43, 35);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Kite Runner', 'English', 2003, 31.50, 44, 36);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Valley of the Dolls', 'English', 1966, 31.00, 45, 14);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Alcoholics Anonymous Big Book', 'English', 1939, 30.00, 46, 12);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('How to Win Friends and Influence People', 'English', 1936, 30.00, 47, 12);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Great Gatsby', 'English', 1925, 30.00, 48, 37);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Gone with the Wind', 'English', 1936, 30.00, 49, 1);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Rebecca', 'English', 1938, 30.00, 50, 38);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Nineteen Eighty-Four', 'English', 1949, 30.00, 51, 39);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Revolt of Mamie Stover', 'English', 1951, 30.00, 52, 40);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Girl with the Dragon Tattoo (Män som hatar kvinnor)', 'Swedish', 2005, 30.00, 53, 40);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Lost Symbol', 'English', 2009, 30.00, 10, 40);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Hunger Games', 'English', 2008, 29.00, 54, 41);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('James and the Giant Peach', 'English', 1961, 28.00, 55, 17);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Young Guard (Молодая гвардия)', 'Russian', 1945, 26.00, 56, 42);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Who Moved My Cheese?', 'English', 1998, 29.00, 57, 43);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('A Brief History of Time', 'English', 1988, 25.00, 58, 44);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Paul et Virginie', 'French', 1788, 25.00, 59, 14);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Lust for Life', 'English', 1934, 25.00, 60, 45);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Wind in the Willows', 'English', 1908, 25.00, 61, 18);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The 7 Habits of Highly Effective People', 'English', 1989, 25.00, 62, 12);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Virgin Soil Upturned (Поднятая целина)', 'Russian', 1935, 24.00, 63, 14);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Celestine Prophecy', 'English', 1993, 23.00, 64, 46);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Fault in Our Stars', 'English', 2012, 23.00, 65, 47);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Girl on the Train', 'English', 2015, 23.00, 66, 48);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Shack', 'English', 2007, 22.50, 67, 14);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Uncle Styopa (Дядя Стёпа)', 'Russian', 1936, 21.00, 68, 24);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Godfather', 'English', 1969, 21.00, 69, 49);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Love Story', 'English', 1970, 21.00, 70, 50);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Catching Fire', 'English', 2009, 21.00, 54, 51);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Mockingjay', 'English', 2010, 20.00, 54, 52);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Kitchen (キッチン)', 'Japanese', 1988, 20.00, 71, 53);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Andromeda Nebula (Туманность Андромеды)', 'Russian', 1957, 20.00, 72, 54);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Autobiography of a Yogi (योगी कथामृत)', 'Hindi', 1946, 20.00, 73, 55);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Gone Girl', 'English', 2012, 20.00, 74, 56);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('All Quiet on the Western Front (Im Westen nichts Neues)', 'German', 1929, 20.00, 75, 57);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Bermuda Triangle', 'English', 1974, 20.00, 76, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Things Fall Apart ', 'English', 1958, 20.00, 77, 14);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Animal Farm ', 'English', 1945, 20.00, 51, 59);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Wolf Totem (狼图腾)', 'Chinese', 2004, 20.00, 78, 60);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Happy Hooker: My Own Story', 'English', 1971, 20.00, 79, 61);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Jaws', 'English', 1974, 20.00, 80, 48);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Love You Forever', 'English', 1986, 20.00, 81, 62);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Women''s Room', 'English', 1977, 20.00, 82, 63);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('What to Expect When You''re Expecting', 'English', 1984, 20.00, 83, 64);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Adventures of Huckleberry Finn', 'English', 1885, 20.00, 84, 65);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Secret Diary of Adrian Mole, Aged 13¾', 'English', 1982, 20.00, 85, 66);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Pride and Prejudice', 'English', 1813, 20.00, 86, 67);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Kon-Tiki: Across the Pacific in a Raft (Kon-Tiki ekspedisjonen)', 'Norwegian', 1950, 20.00, 87, 68);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Good Soldier Švejk (Osudy dobrého vojáka Švejka za světové války)', 'Czech', 1923, 20.00, 88, 69);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Where the Wild Things Are', 'English', 1963, 20.00, 89, 70);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Power of Positive Thinking', 'English', 1952, 20.00, 90, 12);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Secret', 'English', 2006, 20.00, 91, 12);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Fear of Flying', 'English', 1973, 20.00, 92, 71);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Dune', 'English', 1965, 20.00, 93, 54);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Charlie and the Chocolate Factory', 'English', 1964, 20.00, 55, 72);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Naked Ape', 'English', 1968, 20.00, 94, 73);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Where the Crawdads Sing', 'English', 2018, 18.00, 95, 74);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Totto-chan, the Little Girl at the Window (窓ぎわのトットちゃん)', 'Japanese', 1981, 18.00, 96, 75);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Matilda', 'English', 1988, 17.00, 55, 22);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Book Thief', 'English', 2005, 16.00, 97, 76);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Horse Whisperer', 'English', 1995, 16.00, 98, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Goodnight Moon', 'English', 1947, 16.00, 99, 22);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Neverending Story (Die unendliche Geschichte)', 'German', 1979, 16.00, 100, 22);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('All the Light We Cannot See', 'English', 2014, 15.30, 101, 77);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Fifty Shades of Grey', 'English', 2011, 15.20, 102, 78);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Outsiders', 'English', 1967, 15.00, 103, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Guess How Much I Love You', 'English', 1994, 15.00, 104, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Shōgun', 'English', 1975, 15.00, 105, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Poky Little Puppy', 'English', 1942, 15.00, 106, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Pillars of the Earth', 'English', 1989, 15.00, 107, 1);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Perfume (Das Parfum)', 'German', 1985, 15.00, 108, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Grapes of Wrath', 'English', 1939, 15.00, 109, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Shadow of the Wind (La sombra del viento)', 'Spanish', 2001, 15.00, 110, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Interpreter of Maladies', 'English', 2000, 15.00, 111, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Becoming', 'English', 2018, 14.00, 112, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Hitchhiker''s Guide to the Galaxy', 'English', 1979, 14.00, 113, 79);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Tuesdays with Morrie', 'English', 1997, 14.00, 114, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('God''s Little Acre', 'English', 1933, 14.00, 115, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Follow Your Heart (Va'' dove ti porta il cuore)', 'Italian', 1994, 14.00, 116, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('A Wrinkle in Time', 'English', 1962, 14.00, 117, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Long Walk to Freedom', 'English', 1994, 14.00, 118, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Old Man and the Sea', 'English', 1952, 13.00, 119, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Life After Life', 'English', 1975, 13.00, 120, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Peyton Place ', 'English', 1956, 12.10, 121, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Giver', 'English', 1993, 12.00, 122, 80);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Me Before You', 'English', 2012, 12.00, 123, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Norwegian Wood (ノルウェイの森)', 'Japanese', 1987, 12.00, 124, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Plague (La Peste)', 'French', 1947, 12.00, 125, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('No Longer Human (人間失格)', 'Japanese', 1948, 12.00, 126, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Man''s Search for Meaning (Ein Psychologe erlebt das Konzentrationslager)', 'German', 1946, 12.00, 127, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Divine Comedy (La Divina Commedia)', 'Italian', 1304, 11.50, 128, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Prophet', 'English', 1923, 11.00, 129, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Boy in the Striped Pyjamas', 'English', 2006, 11.00, 130, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Exorcist', 'English', 1971, 11.00, 131, 81);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Gruffalo', 'English', 1999, 10.50, 132, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Fifty Shades Darker', 'English', 2012, 10.40, 102, 78);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Tobacco Road', 'English', 1932, 10.00, 115, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Ronia, the Robber''s Daughter', 'Swedish', 1981, 10.00, 133, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Cat in the Hat', 'English', 1957, 10.50, 134, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Diana: Her True Story', 'English', 1992, 10.00, 135, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Help', 'English', 2009, 10.00, 136, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Catch-22', 'English', 1961, 10.00, 137, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Stranger (L''Étranger)', 'French', 1942, 10.00, 125, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Eye of the Needle', 'English', 1978, 10.00, 107, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Lovely Bones', 'English', 2002, 10.00, 138, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Wild Swans', 'English', 1992, 10.00, 139, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Santa Evita', 'Spanish', 1995, 10.00, 140, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Night (Un di Velt Hot Geshvign)', 'Yiddish', 1958, 10.00, 141, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Confucius from the Heart (于丹《论语》心得)', 'Chinese', 2006, 10.00, 142, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Total Woman', 'English', 1974, 10.00, 143, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Knowledge-value Revolution (知価革命)', 'Japanese', 1985, 10.00, 144, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Problems in China''s Socialist Economy (中国社会主义经济问题研究)', 'Chinese', 1979, 10.00, 145, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('What Color Is Your Parachute?', 'English', 1970, 10.00, 146, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Dukan Diet', 'French', 2000, 10.00, 147, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Joy of Sex', 'English', 1972, 10.00, 148, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Gospel According to Peanuts', 'English', 1965, 10.00, 149, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Subtle Art of Not Giving a Fuck', 'English', 2016, 10.00, 150, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Life of Pi', 'English', 2001, 10.00, 151, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Front Runner', 'English', 1974, 10.00, 152, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Goal', 'English', 1984, 10.00, 153, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Fahrenheit 451', 'English', 1953, 10.00, 154, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Angela''s Ashes', 'English', 1996, 10.00, 155, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('The Story of My Experiments with Truth (સત્યના પ્રયોગો અથવા આત્મકથા)', 'Gujarati', 1929, 10.00, 156, 58);
INSERT INTO livros (nome, idioma, ano_publicacao, vendas, autor_id, genero_id) VALUES ('Bridget Jones''s Diary', 'English', 1996, 10.00, 157, 58);
